const BLOCKS_TYPES = {
  EMPTY: '|',
  TYPE_A: 'A',
  TYPE_B: 'B',
  TYPE_A_SPECIAL: '@',
  TYPE_B_SPECIAL: '%',
  DELETION_TYPE_A: 'a',
  DELETION_TYPE_B: 'b',
  DELETION_TYPE_A_SPECIAL: '*',
  DELETION_TYPE_B_SPECIAL: '~',
  SWEEP_TYPE_A: 'S',
  SWEEP_TYPE_B: 's',
  SWEEP_TYPE_A_SPECIAL: '#',
  SWEEP_TYPE_B_SPECIAL: '$',
};

export { BLOCKS_TYPES };
